# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_authtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='user',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('UserManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
