# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170219_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('description', models.CharField(default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_group',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Group'),
        ),
    ]
