# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 04:00
from __future__ import unicode_literals

from django.db import migrations, models

def install_groups(apps, schema_editor):
    Group = apps.get_model('app', 'Group')
    groups = [
        {'name': 'admin', 'description': 'Administration'},
        {'name': 'All', 'description': 'Top level group, has access to all below'},
        {'name': 'USM', 'description': 'University of Southern Maine'}
    ]

    for g in groups:
        group, created = Group.objects.get_or_create(name = g['name'], description = g['description'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170219_0352'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RunPython(install_groups),
    ]
