# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170219_0400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Company',
        ),
        migrations.AlterModelTable(
            name='company',
            table='user_company',
        ),
    ]
