# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170305_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaditem',
            name='timestamp',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
