# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170319_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaditem',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
