# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170319_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='full_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='full_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='thumb_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='thumb_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='full_size',
            field=models.ImageField(default='', height_field='full_height', upload_to='images/fullsize', width_field='full_width'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumb',
            field=models.ImageField(default='', height_field='thumb_height', upload_to='images/thumbs', width_field='thumb_width'),
        ),
    ]
